version: '3'

services:
  vite_docker:
    image: node:alpine
    container_name: vite_docker
    entrypoint: /bin/sh
    command: -c "npm install && npm run dev"
    ports:
      - 8001:8001
    working_dir: /frontend
    volumes:
      - type: bind
        source: ./frontend
        target: /frontend
    tty: true
    depends_on:
      - backend
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
