repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black src/
        language: system
        pass_filenames: false
        types: [python]

      - id: isort
        name: isort
        entry: poetry run isort src/
        language: system
        pass_filenames: false
        types: [python]

      - id: flake8
        name: flake8
        entry: poetry run flake8 src/
        language: system
        pass_filenames: false
        types: [python]

      - id: pylint
        name: pylint
        entry: poetry run pylint src/
        language: system
        pass_filenames: false
        types: [python]

      - id: mypy
        name: mypy
        entry: poetry run mypy src/
        language: system
        pass_filenames: false
        types: [python]

      - id: darglint
        name: darglint
        entry: poetry run darglint src/
        language: system
        pass_filenames: false
        types: [python]
