"""
Revision ID: 0bd1803d7a14

Revises:
Create Date: 2023-06-15 09:16:30.002565

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0bd1803d7a14"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade function. It is called when you run alembic upgrade head."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chapters",
        sa.Column("chapter_id", sa.UUID(), nullable=False),
        sa.Column("chapter_name", sa.String(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("chapter_id"),
    )
    op.create_index(
        op.f("ix_chapters_chapter_name"),
        "chapters",
        ["chapter_name"],
        unique=True,
    )
    op.create_table(
        "committees",
        sa.Column("committee_id", sa.UUID(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("phone", sa.String(), nullable=True),
        sa.Column("chapter_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["chapter_id"],
            ["chapters.chapter_id"],
        ),
        sa.PrimaryKeyConstraint("committee_id"),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade function. It is called when you run alembic downgrade base."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("committees")
    op.drop_index(op.f("ix_chapters_chapter_name"), table_name="chapters")
    op.drop_table("chapters")
    # ### end Alembic commands ###
