"""
Revision ID: 7f1bf0c73c51

Revises:
Create Date: 2023-05-01 22:17:48.797040.
"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "7f1bf0c73c51"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """
    Upgrade to 7f1bf0c73c51 revision.

    This revision adds the chapters table.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    chapters = op.create_table(
        "chapters",
        sa.Column(
            "id",
            sa.UUID(),
            nullable=False,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("chapter_name", sa.String(), nullable=False),
        sa.Column(
            "is_deleted",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_chapters_chapter_name"),
        "chapters",
        ["chapter_name"],
        unique=True,
    )
    op.bulk_insert(
        chapters,
        [
            {"chapter_name": "Chapter 1"},
            {"chapter_name": "Chapter 2"},
            {"chapter_name": "Chapter 3"},
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Downgrade from 7f1bf0c73c51 revision.

    This revision removes the chapters table.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_chapters_chapter_name"), table_name="chapters")
    op.drop_table("chapters")
    # ### end Alembic commands ###
