name: Testing

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Linting_Formatting_Testing:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.1'

    - name: Install dependencies
      run: pip install -r backend/requirements.txt

    - name: Run black
      working-directory: backend
      run: black src

    - name: Run isort
      working-directory: backend
      run: isort src

    - name: Run ruff
      working-directory: backend
      run: ruff check .

    - name: Install docker-compose
      run: pip install docker-compose

    - name: Build and test
      working-directory: backend
      run: |
        docker-compose build
        docker-compose up -d
        docker exec backend sh ./scripts/migrate.sh
        docker exec backend coverage run -m pytest
        docker exec backend coverage report

