name: Testing

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  linting-and-formatting:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.1'

    - name: Install dependencies
      run: pip install -r backend/requirements.txt

    - name: Run black
      working-directory: backend
      run: black src

    - name: Run isort
      working-directory: backend
      run: isort src

    - name: Run ruff
      working-directory: backend
      run: ruff check .

  pytest-with-coverage:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.1'

      - name: Install dependencies
        run: pip install -r src/requirements.txt

      - name: Run pytest with coverage
        working-directory: backend
        run: pytest --cov=my_project testing

      - name: Check coverage
        working-directory: backend
        run: |
          COVERAGE=$(coverage report | grep TOTAL | awk '{print $NF}' | tr -d '%')
          if [ $COVERAGE != 100 ]; then
            echo "Coverage is not 100%"
            exit 1
          fi
